# Site settings
author: Otto
title: Otto's Coding Blog
header-img: img/home-bg.png
email: otto@ottostacos.com
copyright_name: Otto
description: > # this means to ignore newlines until "baseurl:"
  My quest to solve a sea of endless error messages
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ottocedeno

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
